### PR TITLE
multi socket test change test.

### PR DESCRIPTION
**Pull request by Akayeshmantha**

### CODE REVIEW

**Comment by membphis** [comment]
how about this style? it seems simpler.

```lua
local logger_socket = require "resty.logger.socket"
local logger = logger_socket:new({
    host = "127.0.0.1",
    port = 29999,
    flush_limit = 1,
})

local bytes, err = logger:log(ngx.var.request_uri)
ngx.say("done")
if not ok then
    ngx.say(err)
end
```

**Comment by Akayeshmantha** [comment]
Hi @membphis  dont we need to check the logger is initted. If so it will help to maintain the bulk requests as the readme mentioned? 

If its initted no need to create new logger ? I think we should get the usage of it to make sure it will be sending logs in a bulck?

Wdyt?

**Comment by membphis** [comment]
> dont we need to check the logger is initted

I think we can call the init function in `new` method, and we can do more initialization things.

Not only need to change the test cases, but also need to update the source code.

**Comment by membphis** [comment]
if the logger object is a global object, we can use this style, it is fine.

```lua
local logger_socket = require "resty.logger.socket"
if not logger_socket.initted() then
    local ok, err = logger_socket.init{
        host = 'xxx',
        port = 1234,
        flush_limit = 1234,
        drop_limit = 5678,
    }
    if not ok then
        ngx.log(ngx.ERR, "failed to initialize the logger: ",
                err)
        return
    end
end
```

But we need to create multiple logger objects, which can be connected to different log servers.

That is why I think the new style is better. Different `logger's are completely independent.

```lua
local logger_socket = require "resty.logger.socket"
local logger = logger_socket:new({
    host = "127.0.0.1",
    port = 29999,
    flush_limit = 1,
})

local bytes, err = logger:log(ngx.var.request_uri)
ngx.say("done")
if not ok then
    ngx.say(err)
end
```

**Comment by Akayeshmantha** [comment]
Yes 🙂 I got you now.

**Comment by Akayeshmantha** [comment]
@membphis  I think we cant actually hide init method but we can do something like this. For multi socket purpose.

```shell
__DATA__
=== TEST 1: create 2 logger_socket oblects
--- http_config eval
"$::HttpConfig"
. q{
    server {
        listen 29999;
    }
}
--- config
    location = /t {
        content_by_lua_block {
            collectgarbage()  -- to help leak testing
            local logger_socket = require "resty.logger.socket"
            local logger = logger_socket:new()
            local ok, err = logger:init{
                host = "127.0.0.1",
                port = 29999,
                flush_limit = 1,
            }
            local bytes, err = logger:log(ngx.var.request_uri)
            ngx.say("done")
            if not ok then
                ngx.say(err)
            end
        }
    }
--- request
GET /t
--- response_body
done
--- no_error_log
[error]
```

**Comment by Akayeshmantha** [comment]
@membphis  I added more test cases can u have a look an confirm they are in the right way. 

Then we will continue and push all tests.

**Comment by membphis** [comment]
> I think we cant actually hide init method but we can do something like this. For multi socket purpose.

I do not think that is a good design.

One `logger' object can only bind one socket. If we want send data to different log server, we need create multiple logger object.

For one log server, we can reuse the logger object.

Here is the example code:

```lua
local core = require("apisix.core")
local lrucache = core.lrucache.new({
    ttl = 300, count = 512
})

-- log phase in APISIX
function _M.log(conf, ctx)
    -- fetch it from lrucache
    local logger_socket = require("resty.logger.socket")
    local logger = lrucache("127.0.0.1", "29999", logger_socket.new, {
        host = "127.0.0.1",
        port = 29999,
        flush_limit = 1,
    })

    -- reuse the logger object
    local bytes, err = logger:log(ngx.var.request_uri)
    ngx.say("done")
    if not ok then
        ngx.say(err)
    end
end
```

**Comment by membphis** [comment]
any news?

**Comment by Akayeshmantha** [comment]
Yes I got you this is creating new socket in the :new() phase init()  is a library method to initialize the host connection. It will create a new socket and initliaze the connection.

for an example 

```nginx
 location = /t {
          content_by_lua_block {
            collectgarbage()  -- to help leak testing
            local logger_socket = require "resty.logger.socket"
            local logger = logger_socket:new()
            local ok, err = logger:init{
                flush_limit = 1,
                drop_limit = 2,
                retry_interval = 1,
                timeout = 100,
            }
            if not ok then
                ngx.say(err)
            end
        }
```

Here it's creating a new socket as you can see it's calling its own init method to initialize the connection with the remote host .

WDYT?

**Comment by Akayeshmantha** [comment]
@membphis sorry I didnt see the above comment

**Comment by membphis** [comment]
> Yes I got you this is creating new socket in the :new() phase init() is a library method to initialize the host connection.

Because we are creating logger objects through the `new` method, we no longer need the` init` method. Otherwise, users will be confused.

```nginx
location = /t {
    content_by_lua_block {
        collectgarbage()  -- to help leak testing
        local logger_socket = require "resty.logger.socket"
        local logger, err = logger_socket:new({
            flush_limit = 1,
            drop_limit = 2,
            retry_interval = 1,
            timeout = 100,
        })
        
        if not logger then
            ngx.say(err)
        end
    }
}
```

**Comment by Akayeshmantha** [comment]
@membphis  sorry for the late reply last week was quite busy here.

__DATA__
=== TEST 1: create 2 logger_socket oblects
--- http_config eval
"$::HttpConfig"
. q{
    server {
        listen 29999;
    }
}
--- config
    location = /t {
        content_by_lua_block {
            collectgarbage()  -- to help leak testing
            local logger_socket = require "resty.logger.socket"
            local logger = logger_socket:new({
                host = "127.0.0.1",
                port = 29999,
                flush_limit = 1,
            })
            local bytes, err = logger:log(ngx.var.request_uri)
            ngx.say("done")
            if not ok then
                ngx.say(err)
            end
        }
    }
--- request
GET /t
--- response_body
done
--- no_error_log
[error]

when I run the above test as you mention am getting below error.

  Failed test 'TEST 1: create 2 logger_socket oblects - response_body - response is expected (repeated req 0, req 0)'
   at /usr/local/share/perl/5.26.1/Test/Nginx/Socket.pm line 1382.
          got: 'done
 not initialized
 '
     expected: 'done
 '

   Failed test 'TEST 1: create 2 logger_socket oblects - response_body - response is expected (repeated req 1, req 0)'
   at /usr/local/share/perl/5.26.1/Test/Nginx/Socket.pm line 1382.
          got: 'done
 not initialized
 '
     expected: 'done
 '
 Looks like you failed 2 tests of 6.
t/multi_socket.t .. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/6 subtests 

Test Summary Report
-------------------
t/multi_socket.t (Wstat: 512 Tests: 6 Failed: 2)
  Failed tests:  2, 5
  Non-zero exit status: 2
Files=1, Tests=6,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.10 cusr  0.02 csys =  0.14 CPU)
Result: FAIL


It says not initialized. What are we going to do here change the code of the library?

**Comment by Akayeshmantha** [comment]
@membphis any idea 🙂

**Comment by membphis** [comment]
@Akayeshmantha we need to update the source code of https://github.com/api7/lua-resty-logger-socket/blob/master/lib/resty/logger/socket.lua

make it support this style:

```lua
location = /t {
    content_by_lua_block {
        collectgarbage()  -- to help leak testing
        local logger_socket = require "resty.logger.socket"
        local logger, err = logger_socket:new({
            flush_limit = 1,
            drop_limit = 2,
            retry_interval = 1,
            timeout = 100,
        })
        
        if not logger then
            ngx.say(err)
        end
    }
}
```

I will submit a new PR to implement the first step.

Then you can continue to do the latter things.

**Comment by membphis** [comment]
@Akayeshmantha I created a PR right now, please take a look when you have time.

https://github.com/api7/lua-resty-logger-socket/pull/4/files#diff-a653f92791f0acebaa0de576a1926a74R69-R83

**Comment by Akayeshmantha** [comment]
Woow thanks alo @membphis  😃

**Comment by Akayeshmantha** [comment]
@membphis  this PR is ready for review.

**Comment by membphis** [comment]
I think we can merge this PR first. 
Then you can rebase master for PR https://github.com/api7/lua-resty-logger-socket/pull/9 .

And we can confirm if it works fine in Travis CI.

**Pull request merged**
