### PR TITLE
[WIP] Add travis file.

### PR DESCRIPTION
**Pull request by Akayeshmantha**

### CODE REVIEW

**Comment by membphis** [comment]
I have enabled the travis  CI right now. you can make a try again.

**Comment by membphis** [comment]
we need to rebase this current branch

**Comment by membphis** [comment]
@Akayeshmantha congratulations, it works fine.

image

**Comment by membphis** [comment]
@Akayeshmantha do you think it the time to release a new version? then we can use it by luarocks.

**Comment by Akayeshmantha** [comment]
@membphis  sure shalle we release it so I can reuse this  one in apisix 😃

**Comment by membphis** [comment]
@Akayeshmantha I have release new version v2.0. you can continue your job now 😃

**Comment by Akayeshmantha** [comment]
@membphis  thanks alot

**Pull request merged**
